export default {
	BACKGROUND_MOVING: 1,
	BACKGROUND_UI: 2,
	BACKGROUND_BEHIND: 3,
	CONNECTORS: 4,
	PROJECTILES: 5,
	WEAPONS: 6,
	ITEMS: 7,
	MOBS: 8,
	EXPLOSIONS: 9,
	BACKGROUND_MAIN: 10,
	BACKGROUND_BEFORE: 11,
	DARKEN: 12,
	SUBMARINE: 13,
	UI_1: 14,
	UI_2: 15
};