export default {
	BACKGROUND_MOVING: 1,
	BACKGROUND_UI: 2,
	BACKGROUND_BEHIND: 3,
	ITEMS: 4,
	MOBS: 5,
	EXPLOSIONS: 6,
	BACKGROUND_MAIN: 7,
	BACKGROUND_BEFORE: 8,
	DARKEN: 9,
	CONNECTORS: 10,
	PROJECTILES: 11,
	WEAPONS: 12,
	SUBMARINE: 13,
	UI_1: 14,
	UI_2: 15
};